# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90ed3020f39057cb0ec6c8989668e5c53c623a4a75217217ccf642bcaac6b43826a9bbfea1f535715baf945a031d503161a3b4dbbb1fa672cbc20b66e7e6f1e6

test:
  secret_key_base: 493e7a7d220d833c5ff6dc28a226fa09fea4b94b68b0f5f4fe73d4ee3dd2b8e31868d5082c1e1ee21363728c7214e6652570d107fc538db3da957b9aa4b06943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
